"""Convert cookie JSON to Netscape format (yt-dlp / curl compatible)."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def write_netscape_cookie_file(cookies: list[dict[str, Any]], output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(_to_netscape(cookies), encoding="utf-8")
    return output_path


def _to_netscape(cookies: list[dict[str, Any]]) -> str:
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by On1y. https://curl.haxx.se/docs/http-cookies.html",
        "",
    ]
    for raw in cookies:
        name = raw.get("name")
        value = raw.get("value")
        if not name or value is None:
            continue
        domain = str(raw.get("domain") or "")
        if domain and not domain.startswith("."):
            domain = f".{domain}"
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = str(raw.get("path") or "/")
        secure = "TRUE" if raw.get("secure") else "FALSE"
        expires = raw.get("expires")
        # Playwright session cookies use -1; Netscape/yt-dlp expect 0 for session
        if expires in (None, "", 0, -1) or (isinstance(expires, (int, float)) and expires < 0):
            expiry = "0"
        else:
            expiry = str(int(expires))
        lines.append(
            "\t".join(
                [
                    domain,
                    include_subdomains,
                    path,
                    secure,
                    expiry,
                    str(name),
                    str(value),
                ]
            )
        )
    return "\n".join(lines) + "\n"
